### PR TITLE
Add reset functionality

### PR DESCRIPTION
**Pull request by yn5**
Add functionality that resets / erases the text immediately when the typing property is set to -2.

### CODE REVIEW

**Comment by yn5** [comment]
@ianbjorndilling @frostney Could this get merged please?

**Comment by frostney** [comment]
Hi @yn5, first of all thank you for your time and effort you put into this. 🎉 

I do have a couple of questions before merging this in:
- Could you walk me through why we need `babel-preset-react-hmre` here?
- I am not completely a fan of having the reset functionality tied to the `typing` prop. What do you think about having a reset method and calling it with `this.refs.typewriter.reset()` when defining a typewriter ref?

**Comment by yn5** [comment]
Hi @frostney. Thanks for the feedback!
- My text editor (Atom) gave me an error saying it couldn't find `babel-preset-react-hmre`, so I added the dependency. It might have thrown the error for another reason so if you think `babel-preset-react-hmre` is not necessary I wouldn't mind removing the commit.
- I am fine with that proposal, I'll change the pull request to reflect it.

**Comment by frostney** [comment]
Thank you for the explanation. Please leave `babel-preset-react-hmre` in there, while I haven't run into this issue myself (also using Atom), others might run into the issue you encountered.

**Comment by yn5** [comment]
@frostney I have implement your suggested proposal. Could you please have a look and merge if it's ok (or provide some more feedback if not)?

**Comment by frostney** [comment]
Looks good to me. Thank you 👍

**Comment by frostney** [comment]
I just released `0.4.0` and these changes are part of it. 👍

**Pull request merged**
