### PR TITLE
Fix eslint errors and clean up code

### PR DESCRIPTION
**Pull request by yn5**
Since I plan to do some more work on this module I would like to propose a little more consistency in the code. Just a suggestion, hope you guys like it.

### CODE REVIEW

**Comment by frostney** [comment]
Big thumbs up on this one! 👍 
Thank you!

**Comment by frostney** [comment]
I would like to update to the latest ESLint guidelines at some point, but I feel that's out of the scope for this pull request.

**Comment by yn5** [comment]
@frostney Yeah I think it would be good to have some code style enforcing mechanism, maybe extend some commonly used eslint config like `airbnb` (although that one differs quite much from the current code style).

And thanks for merging again by the way!

**Comment by frostney** [comment]
I usually go with AirBnB + precommit hook to enforce the guideline in other projects. Let me think about what we can do here, but feel free to leave any suggestions you may have either here or as a separate pull request.

**Pull request merged**
